### ISSUE TITLE
环境langchain版本问题

### ISSUE THREAD

**Issue by hui-max** [zjunlp/AutoAct#11]
能否列出环境中langchain相关的版本号或是整个环境中的配置，非常感谢

**Comment by hui-max** [comment]
ImportError: cannot import name 'AIMessage' from 'langchain.prompts.chat'一直在报这样一个错误，更改了langchain相关版本后并无效果

**Comment by GoooDte** [comment]
您好，可以尝试一下langchain==0.0.299

**Comment by hui-max** [comment]
谢谢，这个方法有帮助，但又报了另一个错误
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b8dec086800>: Failed to establish a new connection: [Errno 111] Connection refused')).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b8dec0872b0>: Failed to establish a new connection: [Errno 111] Connection refused')).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b8dec085c30>: Failed to establish a new connection: [Errno 111] Connection refused')).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b8dec270a60>: Failed to establish a new connection: [Errno 111] Connection refused')).
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2b8dec272a10>: Failed to establish a new connection: [Errno 111] Connection refused')).
have generated num 2, all 800 need to be generated all
Traceback (most recent call last):
  File "/HOME/scw6dlp/.conda/envs/public/lib/python3.10/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/HOME/scw6dlp/.conda/envs/public/lib/python3.10/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/HOME/scw6dlp/.conda/envs/public/lib/python3.10/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
请问这是什么原因呢

**Comment by GoooDte** [comment]
您好，看您的报错应该是调用模型时候的网络问题。
如果您用的是openai闭源模型，建议您使用科学上网的方式；
如果您用的是开源模型，请检查您的模型部署是否正确
