### ISSUE TITLE
Evaluation about the baseline?

### ISSUE THREAD

**Issue by EmeryBAI** [zjunlp/AutoAct#12]
How can I run the baseline mentioned in the paper (e.g. ReAct, CoT, ReWOO) by this repo？

**Comment by GoooDte** [comment]
Thank you for your interest in our work!
Due to the various code frameworks of different baselines, it is challenging to integrate them into a single repository. We have listed all the corresponding repositories for the baselines we used in the README. You can refer to them for more reference.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by EmeryBAI** [comment]
Just a suggestion, you should fix some detail problems like: variable named: **temprature** which can lead errors.

**Comment by zxlzr** [comment]
Thank you for your suggestion, we will fix it soon.

**Comment by EmeryBAI** [comment]
Btw, do you provide some few-shot templates for the ReAct and CoT methods?

**Comment by GoooDte** [comment]
Our few shot prompt for ReAct and CoT is referenced here https://github.com/anchen1011/FireAct/tree/main/prompts

**Comment by EmeryBAI** [comment]
Thanks for your reply. I have checked the FireAct repo. There seem no few shot prompts for scienceQA, which is also one of your baseline dataset. Would you mind tell me where the template is?

**Comment by BeasterYong** [comment]
Hello, considering the cleanliness of the project, we did not include the prompt for the scienceqa section in the project repository. You can directly use the following prompt:
- ScienceQA-COT

**Comment by zxlzr** [comment]
hi, do you have any further questions?
