### ISSUE TITLE
How to deploy llama2-13b-chat + lora via fastchat?

### ISSUE THREAD

**Issue by ro-ko** [zjunlp/AutoAct#14]
Hello! I have finished training and am now trying to run `run_eval.sh`. Could you tell me how to deploy the trained llama model with lora? I checked the reference docs in [here](https://github.com/lm-sys/FastChat/blob/main/docs/langchain_integration.md), but still I don't know how to do and met too many errors.

**Comment by Rolnand** [comment]
replace the model path in [https://github.com/zjunlp/AutoAct/blob/main/Scripts/model_bash/single_model.sh](url) with your lora file path
