### ISSUE TITLE
experimental trajectory

### ISSUE THREAD

**Issue by dongdong-yan** [zjunlp/AutoAct#4]
Thank you very much for your work. Can you please share your experimental trajectory? I would be very grateful if you could.

**Comment by GoooDte** [comment]
Sure, we will share our training trajectories soon.

**Comment by dongdong-yan** [comment]
> Sure, we will share our training trajectories soon.

Thank you very much. Also, can you share the output results of the experiment?

**Comment by GoooDte** [comment]
OK. We will inform you once we release them.

**Comment by GoooDte** [comment]
Hello, we have released on [Google Drive](https://drive.google.com/drive/folders/1Sh6Ksj8T0fT23ePWRf_dDcOTmpZlulr2?usp=sharing). Enjoy it!
