### ISSUE TITLE
There is no output when performing Self_Planning/Traj_Syn/run_task.py

### ISSUE THREAD

**Issue by yun-hu** [zjunlp/AutoAct#5]
Hi,
When I execute **Self_Planning/Traj_Syn/run_task.py**, there is no output from **Thought** and **Action**, and there is a warning message, I don't know if you have a solution
![image](https://github.com/zjunlp/AutoAct/assets/68475236/fa27bea8-49ad-4173-a20c-15e2235d1e94)
![image](https://github.com/zjunlp/AutoAct/assets/68475236/f953b42b-e173-441b-83ec-37cc2384f2d4)

**Comment by GoooDte** [comment]
Hi. The warning information can be ignored and it does not affect running.
We have also encountered situations where there is no output during testing, which may be an issue with the llama-2 model itself or the fastchat package. You can try running it a few more times.

**Comment by yun-hu** [comment]
Thank you.
I think I understand why
I used gpt-3.5-turbo and the code did not call successfully

**Comment by yun-hu** [comment]
Add 
**os.environ['OPENAI_API_KEY'] = "" 
os.environ['OPENAI_API_BASE'] = "https://api.openai.com/v1"**
in the class **langchain_openai_chatllm**
