### ISSUE TITLE
KeyError: 'conversations'

### ISSUE THREAD

**Issue by yun-hu** [zjunlp/AutoAct#6]
Hi,
During training, there was no keyword "conversations" in the list **raw_data**
I printed raw_data and found that there were only two keywords, "input" and "output"
is there something I did wrong?
![image](https://github.com/zjunlp/AutoAct/assets/68475236/2e550583-126a-43ca-9402-65a9e8fcd358)

**Comment by Rolnand** [comment]
Could you please provide the code for your test.py function? I'll be happy to help you review it. By the way, I'd like to clarify that in our script train_lora.py, the 'make_supervised_data_module' function is not being utilized , we use 'load_and_process_dataset to do data process

**Comment by yun-hu** [comment]
Thank you for your reply.
Since I ran the code locally, I wrote some of the code that requires command line input into the test.py file
But there may be a problem because some parameters are not passed correctly
After I migrated the project to colab, it runs successfully
Thanks again!
