### ISSUE TITLE
How do I run this project and I'm having some problems

### ISSUE THREAD

**Issue by whfeLingYu** [zjunlp/AutoAct#9]
When I run data_generation directly, the top_k parameter is not displayed in the openai model. I have changed several openai and langchian versions, but there is still no way to solve the default parameter problem
![image](https://github.com/zjunlp/AutoAct/assets/92906901/25e597c8-0c6b-4005-a85e-f9255c7c3887)

**Comment by GoooDte** [comment]
Hello, may I know if you are using an OpenAI model or a locally deployed model using FastChat?

**Comment by whfeLingYu** [comment]
I've tried both, and I have this problem with both native fastchat deployments and direct calls to the openai interface

**Comment by hui-max** [comment]
Hello, I meet this problem too, could you share the way to solve the problem? Thanks a lot
